export { default as Header } from './header/Header'
export { default as Footer } from './footer/Footer'
export { default as AboutRO } from './aboutRO/AboutRO'
export { default as OurServices } from './ourServices/OurServices'
export { default as Projects } from './projects/Projects'
